name: "setup-python"
description: "Ensures to install a python version that's available on Anaconda"
inputs:
  python-version:
    description: "The python version to install (e.g. 3.8)"
    required: true
outputs:
  installed-python-version:
    description: "The installed python version"
    value: ${{ steps.fetch-python-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: get-python-version
      id: get-python-version
      shell: bash
      run: |
        python_version="${{ inputs.python-version }}"
        if [[ "$python_version" == "3.8" ]]; then
          python_version="3.8.12"
        elif [[ "$python_version" == "3.9" ]]; then
          python_version="3.9.10"
        elif [[ "$python_version" == "3.10" ]]; then
          python_version="3.10.2"
        else
          echo "Invalid python version: '$python_version'. Must be one of ['3.8', '3.9', '3.10']"
          exit 1
        fi
        echo "::set-output name=version::$python_version"
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ steps.get-python-version.outputs.version }}